


services:
  db:
    image: mysql:latest
    container_name: adjumany-project-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notetakingdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
